#!/bin/bash
# Author: Andrew Kassab
# Description: Handles tab completion for preciseplanner program
# Date: 4-08-19

PLANNEROPTS="-a -p -n -r -m -h"

# handles completions 
opt_completions(){
    
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}

    # if we are on the 1st argument
    if [ $COMP_CWORD -eq 1 ]; then
        COMPREPLY=($(compgen -W "${PLANNEROPTS}" -- $cur) ) 
    elif [ $COMP_CWORD -eq 2 ]; then
        case "$prev" in
            "--month")
                COMPREPLY=($(compgen -W "${PLATFORMS}" -- $cur))
                ;;
            "-m")
                COMPREPLY=($(compgen -W "${PLATFORMS}" -- $cur))
                ;;
            *)
                return
                ;;
        esac
    fi
}

complete -F opt_completions planner 
